const FEATCH_RECIPES = "FEATCH_RECIPES";
const GET_CUSINE = "GET_CUSINE";
const SET_PRODUCTS = "SET_PRODUCTS";
const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";

export { FEATCH_RECIPES, GET_CUSINE, SET_PRODUCTS, ADD_TO_FAVORITES };
